version: '3.1'
services:
  server:
    image: practice-server:0.1.0
    container_name: server
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./server/template:/template
      # - ./server/logs:/practice-server/logs
      - ./server/config.yml:/practice-server/config.yml
    networks: 
      - privateNetwork
    depends_on: 
      - nginx
  ui:
    image: practice-ui:0.1.0
    container_name: ui
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    networks: 
      - privateNetwork
    depends_on: 
      - nginx
  nginx:
    image: nginx:1.21
    container_name: nginx
    restart: always
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/access.log:/var/log/nginx/access.log
    networks: 
      - privateNetwork
networks:
  privateNetwork:
    external: false